# Generated by Django 4.2.2 on 2023-08-20 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_crm_system', '0003_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password1', models.CharField(max_length=100)),
                ('password2', models.CharField(max_length=100)),
                ('fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate_crm_system.fields')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate_crm_system.project_name')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
