# Generated by Django 4.2.2 on 2023-08-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_crm_system', '0005_assign_to_user_delete_sign_up'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assign_To_User',
        ),
    ]
