# Generated by Django 4.2.2 on 2023-08-20 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_crm_system', '0007_sign_up'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sign_Up',
        ),
    ]
