# Generated by Django 4.2.2 on 2023-08-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_crm_system', '0009_agents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_inquiry',
            name='converted_date',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_inquiry',
            name='remarks',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
