# Generated by Django 4.2.2 on 2023-08-27 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_crm_system', '0010_alter_add_inquiry_converted_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_inquiry',
            name='follow_up_data',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='add_inquiry',
            name='next_follow_up_data',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agents',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
