# Generated by Django 4.2.2 on 2023-08-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_crm_system', '0011_add_inquiry_follow_up_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_inquiry',
            old_name='follow_up_data',
            new_name='follow_up_date',
        ),
        migrations.RenameField(
            model_name='add_inquiry',
            old_name='next_follow_up_data',
            new_name='next_follow_up_date',
        ),
    ]
