# Generated by Django 5.0.4 on 2024-05-05 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_crm_system', '0012_rename_follow_up_data_add_inquiry_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_inquiry',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate_crm_system.assign_to'),
        ),
        migrations.AlterField(
            model_name='add_inquiry',
            name='fields',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate_crm_system.fields'),
        ),
        migrations.AlterField(
            model_name='add_inquiry',
            name='inquiry_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate_crm_system.inquiry_stage'),
        ),
        migrations.AlterField(
            model_name='add_inquiry',
            name='inquiry_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate_crm_system.inquiry_type'),
        ),
        migrations.AlterField(
            model_name='add_inquiry',
            name='interested_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate_crm_system.project_name'),
        ),
        migrations.AlterField(
            model_name='add_inquiry',
            name='selected_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate_crm_system.selected_unit'),
        ),
    ]
